#!/bin/bash
#SBATCH --mem=150G

cd /home/knam/work/sfrugi_WG/SNV/vcf/bysample

/home/knam/save/programs/hiphase-v1.4.0-x86_64-unknown-linux-gnu/hiphase --bam /home/knam/work/sfrugi_WG/SNV/bam/FC_88.bam --vcf FC_88.vcf.gz --output-vcf FC_88.phased.vcf.gz --reference /home/knam/work/sfrugi_WG/SNV/ref/sfC.ver7.fa

