#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=40G
#SBATCH -p unlimitq
module load bioinfo/gatk-4.2.6.1

gatk HaplotypeCaller -R /home/knam/work/sfrugi_WG/SNV/ref/sfC.ver7.fa -I /home/knam/work/sfrugi_WG/SNV/bam/FC03.bam -O /home/knam/work/sfrugi_WG/SNV/gvcf/FC03.g.vcf.gz -ERC GVCF
