#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=120G

module load devel/python/Python-3.11.1 devel/java/17.0.6
module load module load bioinfo/GATK/4.2.6.1

gatk HaplotypeCaller -R /home/knam/work/sfrugi_WG/SNV/ref/sfC.ver7.fa -I /home/knam/work/sfrugi_WG/SNV/bam/FC35.bam -O /home/knam/work/sfrugi_WG/SNV/gvcf/FC35.g.vcf.gz -ERC GVCF
