#!/bin/bash
#SBATCH -c 8

module load devel/python/Python-3.6.3
module load bioinfo/RepeatMasker/4.1.5

cd /home/knam/work/sfrugi_WG/POSITION/TE/repeatmasker

cp /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/seq/assembly/FC02.fa.gz .

RepeatMasker -xsmall -lib /home/knam/work/sfrugi_WG/POSITION/TE/repeatmodeler/RM_2475944.ThuNov282041512024/consensi.fa.classified -dir ./FC02 -pa 8 -e wublast FC02.fa.gz

rm FC02.fa
