#!/bin/bash

zcat /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/seq/assembly/FC33.fa.gz > /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/cds/temp.fa

/home/knam/save/programs/gffread/gffread /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/gff/FC33.gff -g /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/cds/temp.fa -x /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/cds/FC33.cds.fa

rm /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/cds/temp.fa*

