#!/bin/bash

zcat /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/seq/assembly/FC03.fa.gz > /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/filter_pseudo/cds/temp.fa

/home/knam/save/programs/gffread/gffread /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/filter_pseudo/gff/FC03.gff -g /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/filter_pseudo/cds/temp.fa -x /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/filter_pseudo/cds/FC03.cds.fa

rm /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/Final/intact/filter_pseudo/cds/temp.fa*

