#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/test_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/test.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o test.sorted.bam test.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.test -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=test.sorted.bam OUTPUT=test.bam RGID=test RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=test;

rm -rf temp.test
rm test.metricN.log
rm test.raw.bam
rm test.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index test.bam
