#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC72_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC72.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC72.sorted.bam FC72.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC72 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC72.sorted.bam OUTPUT=FC72.bam RGID=FC72 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC72;

rm -rf temp.FC72
rm FC72.metricN.log
rm FC72.raw.bam
rm FC72.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC72.bam
