#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/FR_14_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FR_14.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FR_14.sorted.bam FR_14.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FR_14 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FR_14.sorted.bam OUTPUT=FR_14.bam RGID=FR_14 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FR_14;

rm -rf temp.FR_14
rm FR_14.metricN.log
rm FR_14.raw.bam
rm FR_14.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FR_14.bam
