#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC78_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC78.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC78.sorted.bam FC78.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC78 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC78.sorted.bam OUTPUT=FC78.bam RGID=FC78 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC78;

rm -rf temp.FC78
rm FC78.metricN.log
rm FC78.raw.bam
rm FC78.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC78.bam
