#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC81_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC81.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC81.sorted.bam FC81.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC81 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC81.sorted.bam OUTPUT=FC81.bam RGID=FC81 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC81;

rm -rf temp.FC81
rm FC81.metricN.log
rm FC81.raw.bam
rm FC81.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC81.bam
