#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC04_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC04.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC04.sorted.bam FC04.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC04 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC04.sorted.bam OUTPUT=FC04.bam RGID=FC04 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC04;

rm -rf temp.FC04
rm FC04.metricN.log
rm FC04.raw.bam
rm FC04.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC04.bam
