#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC33_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC33.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC33.sorted.bam FC33.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC33 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC33.sorted.bam OUTPUT=FC33.bam RGID=FC33 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC33;

rm -rf temp.FC33
rm FC33.metricN.log
rm FC33.raw.bam
rm FC33.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC33.bam
