#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC79_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC79.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC79.sorted.bam FC79.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC79 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC79.sorted.bam OUTPUT=FC79.bam RGID=FC79 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC79;

rm -rf temp.FC79
rm FC79.metricN.log
rm FC79.raw.bam
rm FC79.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC79.bam
