#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC_97_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC_97.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC_97.sorted.bam FC_97.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC_97 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC_97.sorted.bam OUTPUT=FC_97.bam RGID=FC_97 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC_97;

rm -rf temp.FC_97
rm FC_97.metricN.log
rm FC_97.raw.bam
rm FC_97.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC_97.bam
