#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC_105_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC_105.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC_105.sorted.bam FC_105.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC_105 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC_105.sorted.bam OUTPUT=FC_105.bam RGID=FC_105 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC_105;

rm -rf temp.FC_105
rm FC_105.metricN.log
rm FC_105.raw.bam
rm FC_105.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC_105.bam
