#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC76_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC76.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC76.sorted.bam FC76.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC76 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC76.sorted.bam OUTPUT=FC76.bam RGID=FC76 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC76;

rm -rf temp.FC76
rm FC76.metricN.log
rm FC76.raw.bam
rm FC76.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC76.bam
