#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC54_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC54.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC54.sorted.bam FC54.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC54 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC54.sorted.bam OUTPUT=FC54.bam RGID=FC54 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC54;

rm -rf temp.FC54
rm FC54.metricN.log
rm FC54.raw.bam
rm FC54.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC54.bam
