#!/bin/bash
#SBATCH -c 8

cd /home/knam/work/sfrugi_WG/SNV/ref

/home/knam/save/programs/minimap2-2.19_x64-linux/minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /home/knam/work/sfrugi_WG/SNV/rawreads/sfC/FC35_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC35.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC35.sorted.bam FC35.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC35 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC35.sorted.bam OUTPUT=FC35.bam RGID=FC35 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC35;

/home/knam/save/programs/samtools-1.9/samtools index FC35.bam

#rm -rf temp.FC35
#rm FC35.metricN.log
#rm FC35.raw.bam
#rm FC35.sorted.bam

