#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC_89_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC_89.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC_89.sorted.bam FC_89.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC_89 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC_89.sorted.bam OUTPUT=FC_89.bam RGID=FC_89 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC_89;

rm -rf temp.FC_89
rm FC_89.metricN.log
rm FC_89.raw.bam
rm FC_89.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC_89.bam
