#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/FR_16_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FR_16.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FR_16.sorted.bam FR_16.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FR_16 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FR_16.sorted.bam OUTPUT=FR_16.bam RGID=FR_16 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FR_16;

rm -rf temp.FR_16
rm FR_16.metricN.log
rm FR_16.raw.bam
rm FR_16.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FR_16.bam
