#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC01_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC01.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC01.sorted.bam FC01.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC01 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC01.sorted.bam OUTPUT=FC01.bam RGID=FC01 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC01;

rm -rf temp.FC01
rm FC01.metricN.log
rm FC01.raw.bam
rm FC01.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC01.bam
