#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC82_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC82.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC82.sorted.bam FC82.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC82 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC82.sorted.bam OUTPUT=FC82.bam RGID=FC82 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC82;

rm -rf temp.FC82
rm FC82.metricN.log
rm FC82.raw.bam
rm FC82.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC82.bam
