#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC52_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC52.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC52.sorted.bam FC52.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC52 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC52.sorted.bam OUTPUT=FC52.bam RGID=FC52 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC52;

rm -rf temp.FC52
rm FC52.metricN.log
rm FC52.raw.bam
rm FC52.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC52.bam
