#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC02_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC02.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC02.sorted.bam FC02.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC02 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC02.sorted.bam OUTPUT=FC02.bam RGID=FC02 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC02;

rm -rf temp.FC02
rm FC02.metricN.log
rm FC02.raw.bam
rm FC02.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC02.bam
