#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC37_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC37.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC37.sorted.bam FC37.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC37 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC37.sorted.bam OUTPUT=FC37.bam RGID=FC37 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC37;

rm -rf temp.FC37
rm FC37.metricN.log
rm FC37.raw.bam
rm FC37.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC37.bam
