#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/FR_10_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FR_10.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FR_10.sorted.bam FR_10.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FR_10 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FR_10.sorted.bam OUTPUT=FR_10.bam RGID=FR_10 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FR_10;

rm -rf temp.FR_10
rm FR_10.metricN.log
rm FR_10.raw.bam
rm FR_10.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FR_10.bam
