#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC32_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC32.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC32.sorted.bam FC32.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC32 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC32.sorted.bam OUTPUT=FC32.bam RGID=FC32 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC32;

rm -rf temp.FC32
rm FC32.metricN.log
rm FC32.raw.bam
rm FC32.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC32.bam
