#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/FR_LS_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FR_LS.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FR_LS.sorted.bam FR_LS.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FR_LS -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FR_LS.sorted.bam OUTPUT=FR_LS.bam RGID=FR_LS RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FR_LS;

rm -rf temp.FR_LS
rm FR_LS.metricN.log
rm FR_LS.raw.bam
rm FR_LS.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FR_LS.bam
