#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC03_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC03.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC03.sorted.bam FC03.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC03 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC03.sorted.bam OUTPUT=FC03.bam RGID=FC03 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC03;

rm -rf temp.FC03
rm FC03.metricN.log
rm FC03.raw.bam
rm FC03.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC03.bam
