#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC_85_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC_85.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC_85.sorted.bam FC_85.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC_85 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC_85.sorted.bam OUTPUT=FC_85.bam RGID=FC_85 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC_85;

rm -rf temp.FC_85
rm FC_85.metricN.log
rm FC_85.raw.bam
rm FC_85.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC_85.bam
