#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC_92_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC_92.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC_92.sorted.bam FC_92.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC_92 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC_92.sorted.bam OUTPUT=FC_92.bam RGID=FC_92 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC_92;

rm -rf temp.FC_92
rm FC_92.metricN.log
rm FC_92.raw.bam
rm FC_92.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC_92.bam
