#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/FR_07_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FR_07.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FR_07.sorted.bam FR_07.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FR_07 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FR_07.sorted.bam OUTPUT=FR_07.bam RGID=FR_07 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FR_07;

rm -rf temp.FR_07
rm FR_07.metricN.log
rm FR_07.raw.bam
rm FR_07.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FR_07.bam
