#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfC/FC55_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FC55.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FC55.sorted.bam FC55.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FC55 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FC55.sorted.bam OUTPUT=FC55.bam RGID=FC55 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FC55;

rm -rf temp.FC55
rm FC55.metricN.log
rm FC55.raw.bam
rm FC55.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index FC55.bam
