#!/bin/bash
#SBATCH -c 8

module load bioinfo/minimap2-2.19

cd /work/knam/sfrugi_WG/SNV/ref

minimap2 -a -t 8 -x map-hifi sfC.ver7.mmi /work/knam/sfrugi_WG/SNV/rawreads/sfR/SL_LS_HiFi.fastq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/SL_LS.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o SL_LS.sorted.bam SL_LS.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.SL_LS -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=SL_LS.sorted.bam OUTPUT=SL_LS.bam RGID=SL_LS RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=SL_LS;

rm -rf temp.SL_LS
rm SL_LS.metricN.log
rm SL_LS.raw.bam
rm SL_LS.sorted.bam

/home/knam/save/programs/samtools-1.9/samtools index SL_LS.bam
