#!/bin/bash
#SBATCH -c 8

module load bioinfo/Minimap/2-2.28

cd /home/knam/work/sfrugi_WG/Assembly_Syntheny/minimap

minimap2 -t 8 -cx asm20 --eqx /home/knam/work/sfrugi_WG/AFS/Flanking/minimap/sfC.ver7.mmi /home/knam/work/sfrugi_WG/GENE_ANNOTATIONS/seq/assembly/FC52.fa.gz > FC52.paf
